'use client';
import { useForm } from 'react-hook-form';
import { zodResolver } from '@hookform/resolvers/zod';
import { z } from 'zod';
import Modal from '@/components/ui/Modal';
import type { CategoryKey,GameState } from '@/engine/Types';
const schema=z.object({amount:z.number().positive().max(100000)});
export default function InspectModal({category,game,onPurchase,onClose,busy,onCare,error}:{category:CategoryKey|'desk';game:GameState;onPurchase:(c:CategoryKey,n:number)=>void;onClose:()=>void;busy:boolean;onCare:(a:'rest'|'tidy')=>void;error:string}){
 const {register,handleSubmit,formState:{errors}}=useForm<z.infer<typeof schema>>({resolver:zodResolver(schema),defaultValues:{}});
 if(category==='desk')return <Modal title="The work desk" onClose={onClose}><div className="object-story"><p>{game.life.stress>=35?'The bills are taking over the desk. It is getting hard to focus.':'A quiet place to work on tomorrow.'}</p><small>Your character works here when a paycheck arrives. Paychecks arrive every 30 days, or through your connected transactions.</small></div><button className="button primary full-width" onClick={onClose}>Back to my day</button></Modal>;
 const stories={food:{title:'The fridge',line:game.life.foodStock<25?'Just a lonely bottle and yesterday’s leftovers.':game.life.foodStock>70?'Something fresh. Something homemade. Enough for tomorrow, too.':'There is still something good to cook.',help:'Groceries refill food supplies and restore energy. Each day uses food. An empty fridge hurts your health.',action:'Bring home groceries'},housing:{title:'Your bed',line:game.housingDeficits?'There is a rent notice on the pillow. Sleep will have to wait.':'A soft landing at the end of a long day.',help:'Pay rent to keep your home. Two missed months mean eviction. Rest once each day to recover energy.',action:'Pay the rent'},utilities:{title:'The lights',line:game.life.powerOn?'The lights are on. The kettle is humming.':'The room has gone quiet. No lights. No warm dinner.',help:'Unpaid utilities cut the power at month end. A $100 payment restores it. Darkness makes it harder to recover energy.',action:'Pay the utility bill'},leisure:{title:'The sofa',line:game.life.clutter>=3?'Shopping boxes everywhere. The excitement did not last as long as the bill.':'Put your feet up. Life needs a little joy, too.',help:'Leisure brings a little happiness. Going over your plan adds stress, drains energy, and leaves clutter behind.',action:'Treat myself'},transit:{title:'Your keys',line:'The world outside is waiting.',help:'Transport spending sends your character out into the world. Keep it within your plan to avoid stress.',action:'Head out'},savings:{title:'The little ledger',line:game.savedTotal>=500?'Small promises to yourself, starting to become something real.':'A place to keep a promise to future you.',help:'Savings transfers build a safety net and unlock room upgrades every $500. Saving borrowed money will not relieve stress.',action:'Put something aside'}};
 const item=stories[category],jar=game.jars[category];
 return <Modal title={item.title} onClose={onClose}><div className="object-story"><p>{item.line}</p><small>{item.help}</small></div>
 {(category==='housing'||category==='leisure')&&<button className="button secondary full-width" disabled={game.isGameOver||busy||(category==='housing'?game.life.lastRestTurn:game.life.lastTidyTurn)===game.metrics.turn} onClick={()=>onCare(category==='housing'?'rest':'tidy')}>{category==='housing'?'Get an early night':'Tidy up the room'} · once today</button>}
 {category==='savings'?<p className="muted">Savings is a verified mission. Use Keep updated with transactions to add a savings transfer and earn coins. It cannot be completed manually.</p>:<form onSubmit={handleSubmit(v=>onPurchase(category,v.amount))}><label>{item.action} ($)<input type="number" min="0.01" step="0.01" {...register('amount',{valueAsNumber:true})}/></label>{errors.amount&&<p className="error" role="alert">Enter a valid positive amount.</p>}{error&&<p role="alert" className="error">{error}</p>}<button className="button primary full-width" disabled={busy||game.isGameOver}>{busy?'A moment…':item.action}</button></form>}
 <details className="object-ledger"><summary>Look at the numbers</summary><div className="inspect-breakdown"><span>Planned<b>${jar.allocatedAmount+jar.rolloverAmount}</b></span><span>Spent<b>${jar.spentAmount}</b></span><span>Left<b>${jar.allocatedAmount+jar.rolloverAmount-jar.spentAmount}</b></span></div></details></Modal>;
}
