import test from 'node:test';
import assert from 'node:assert/strict';
import { createGame, applyTransactions, advanceTurn,careForHome } from '../src/engine/RulesEngine.ts';
import { stateSchema, profileSchema, type BankTransaction, type GameState } from '../src/engine/Types.ts';
import { DEFAULT_PROFILE } from '../src/engine/Constants.ts';
import { findPath, blocked, gridToScreen, screenToGrid } from '../src/components/canvas/IsometricEngine.ts';
const transaction = (overrides: Partial<BankTransaction> = {}): BankTransaction => ({ id: 'test', payerId: 'demo', medium: 'balance', paymentDate: '2026-09-01', amount: 100, description: 'Groceries', category: 'food', kind: 'purchase', ...overrides });
const month = (s: GameState) => Array.from({ length: 30 }).reduce<GameState>(v => advanceTurn(v), s);
test('a fresh game validates and starts with the first paycheck', () => { const s = createGame(); assert.equal(stateSchema.safeParse(s).success, true); assert.equal(s.metrics.cashBalance, 3000); });
test('transactions are idempotent, do not mutate input, and authoritative balance is not debited twice', () => { const s = createGame(); const t = transaction(); const next = applyTransactions(s, [t, t]); assert.equal(next.metrics.cashBalance, 2900); assert.equal(next.transactions.length, 1); assert.equal(s.jars.food.spentAmount, 0); assert.equal(applyTransactions(next, [t]).metrics.cashBalance, 2900); assert.equal(applyTransactions(next, [t], 2500).metrics.cashBalance, 2500); });
test('income is not spending and transfers preserve net worth', () => { const s = createGame(); const saved = applyTransactions(s, [transaction({ category: 'savings', kind: 'saving', amount: 500 })]); assert.equal(saved.savedTotal, 500); assert.equal(saved.metrics.roomLevel, 1); assert.equal(saved.savedTotal + saved.metrics.cashBalance, 3000); const paid = applyTransactions(saved, [transaction({ id: 'income', kind: 'income', amount: 1000 })]); assert.equal(paid.metrics.cashBalance, 3500); assert.equal(paid.jars.food.spentAmount, 0); });
test('month end applies proportional health loss and accumulated rollover once', () => { const s = applyTransactions(createGame(), [transaction({ amount: 120 })]); const next = month(s); assert.equal(next.metrics.health, 92.5); assert.equal(next.jars.food.rolloverAmount, 280); assert.equal(next.jars.food.spentAmount, 0); assert.equal(next.metrics.cashBalance, 5880); assert.equal(next.metrics.turn, 31); assert.equal(advanceTurn(next).metrics.health, 92.5); });
test('two consecutive missed rent months cause eviction and game over is immutable', () => { const next = month(month(createGame())); assert.equal(next.isGameOver, true); assert.match(next.gameOverReason!, /Eviction/); assert.deepEqual(advanceTurn(next), next); assert.deepEqual(applyTransactions(next, [transaction()]), next); });
test('paying rent resets consecutive housing deficits', () => { const first = month(applyTransactions(createGame(),[transaction({id:'food1',amount:240})])); const second = month(applyTransactions(first, [transaction({ category: 'housing', amount: 1000 }),transaction({id:'food2',amount:240})])); assert.equal(second.housingDeficits, 0); assert.equal(second.isGameOver, false); assert.equal(month(second).isGameOver, false); });
test('zero leisure allocation never produces NaN', () => { const next = month(createGame({ ...DEFAULT_PROFILE, allocations: { ...DEFAULT_PROFILE.allocations, leisure: 0 } })); assert.ok(Number.isFinite(next.metrics.happiness)); assert.ok(stateSchema.safeParse(next).success); });
test('bankruptcy triggers below negative one thousand', () => { const s = applyTransactions(createGame(), [transaction({ amount: 4001 })]); assert.equal(s.isGameOver, true); assert.match(s.gameOverReason!, /Bankruptcy/); assert.equal(s.metrics.debtBalance, 1001); });
test('connected runs never invent income', () => { const s = createGame(); s.mode = 'nessie'; const next = month(s); assert.equal(next.metrics.cashBalance, 3000); assert.equal(next.transactions.length, 0); });
test('exhaustion is deterministic when other essentials are met', () => { let s = createGame(); s.metrics.health = 10; s = applyTransactions(s, [transaction({ category: 'housing', amount: 1000 }), transaction({ id: 'power', category: 'utilities', amount: 100 })]); const next = month(s); assert.equal(next.metrics.health, 0); assert.match(next.gameOverReason!, /Exhaustion/); });
test('invalid budgets and corrupt saves are rejected', () => { assert.equal(profileSchema.safeParse({ ...DEFAULT_PROFILE, income: 100 }).success, false); assert.equal(stateSchema.safeParse({ version: 99 }).success, false); });
test('isometric projection round trips tile centers', () => { for (let x = 0; x < 12; x++)
    for (let y = 0; y < 12; y++) {
        const screen = gridToScreen(x + .5, y + .5);
        assert.deepEqual(screenToGrid(screen.screenX, screen.screenY), { gridX: x, gridY: y });
    } });
test('pathfinding routes around furniture using adjacent unblocked cells', () => { const start = { x: 5, y: 5 }; const path = findPath(start, { x: 11, y: 10 }); assert.deepEqual(path.at(-1), { x: 11, y: 10 }); let prev = start; for (const p of path) {
    assert.equal(blocked(p.x, p.y), false);
    assert.equal(Math.abs(p.x - prev.x) + Math.abs(p.y - prev.y), 1);
    prev = p;
} });
test('clicking occupied furniture finds an accessible nearby tile', () => { const path = findPath({ x: 5, y: 5 }, { x: 2, y: 2 }); assert.ok(path.length); assert.equal(blocked(path.at(-1)!.x, path.at(-1)!.y), false); });
test('fractional money is settled to cents',()=>{const s=applyTransactions(createGame(),[transaction({id:'one',amount:0.1}),transaction({id:'two',amount:0.2})]);assert.equal(s.jars.food.spentAmount,0.3);assert.equal(s.metrics.cashBalance,2999.7);});
test('repeated shopping causes stress, fatigue and visible clutter without duplicate penalties',()=>{const initial=createGame();const one=transaction({id:'shop1',category:'leisure',amount:280});const two=transaction({id:'shop2',category:'leisure',amount:280});const s=applyTransactions(initial,[one,two]);assert.equal(s.life.clutter,6);assert.equal(s.life.stress,18);assert.ok(s.life.energy<initial.life.energy);assert.ok(s.metrics.happiness<initial.metrics.happiness);assert.deepEqual(applyTransactions(s,[one,two]),s);});
test('groceries replenish supplies while daily time consumes them',()=>{const initial=createGame();initial.life.foodStock=2;const hungry=advanceTurn(initial);assert.equal(hungry.life.foodStock,0);assert.equal(hungry.metrics.health,98);const fed=applyTransactions(hungry,[transaction({amount:80})]);assert.equal(fed.life.foodStock,32);assert.ok(fed.life.energy>hungry.life.energy);});
test('unpaid power is cut at settlement and a utility payment restores it',()=>{const s=month(createGame());assert.equal(s.life.powerOn,false);const fixed=applyTransactions(s,[transaction({category:'utilities',amount:100})]);assert.equal(fixed.life.powerOn,true);});
test('rest and tidying are available once each day and cannot erase financial damage',()=>{const s=createGame();s.life.energy=30;s.life.clutter=6;s.life.stress=30;const rested=careForHome(s,'rest');assert.equal(rested.life.energy,45);assert.deepEqual(careForHome(rested,'rest'),rested);const tidy=careForHome(rested,'tidy');assert.equal(tidy.life.clutter,4);assert.equal(tidy.life.stress,25);assert.equal(tidy.metrics.cashBalance,s.metrics.cashBalance);assert.deepEqual(careForHome(tidy,'tidy'),tidy);assert.ok(careForHome(advanceTurn(tidy),'rest').life.energy>advanceTurn(tidy).life.energy);});
test('old saves receive compatible life defaults',()=>{const old:Record<string,unknown>={...createGame()};delete old.life;const loaded=stateSchema.parse(old);assert.equal(loaded.life.foodStock,65);assert.equal(loaded.life.lastRestTurn,0);});

