import { spawn } from 'node:child_process';
import { mkdir,writeFile } from 'node:fs/promises';
import path from 'node:path';
import assert from 'node:assert/strict';
const output=path.resolve('artifacts');await mkdir(output,{recursive:true});
const chrome=spawn('C:/Program Files/Google/Chrome/Application/chrome.exe',['--headless=new','--disable-gpu','--no-first-run','--no-default-browser-check','--remote-debugging-port=9224',`--user-data-dir=${path.resolve('.browser-profile')}`,'about:blank'],{windowsHide:true,stdio:'ignore'});
let ws;const pending=new Map();let seq=0;const errors=[];let intercept=()=>{};const reviewRequests=[];const auditRequests=[];let bankSyncs=0;let failReview=false;let severe=false;let severeKind='eviction';
try{
 let pages;for(let i=0;i<50;i++){try{pages=await fetch('http://127.0.0.1:9224/json').then(r=>r.json());if(pages.length)break;}catch{}await new Promise(r=>setTimeout(r,200));}
 if(!pages?.length)throw new Error('Chrome debugging endpoint unavailable');
 ws=new WebSocket(pages[0].webSocketDebuggerUrl);await new Promise((resolve,reject)=>{ws.onopen=resolve;ws.onerror=reject;});
 ws.onmessage=({data})=>{const msg=JSON.parse(data);if(msg.method==='Fetch.requestPaused')void intercept(msg.params);if(msg.id){const p=pending.get(msg.id);pending.delete(msg.id);if(msg.error)p?.reject(new Error(msg.error.message));else p?.resolve(msg.result);}if(msg.method==='Runtime.exceptionThrown')errors.push(msg.params.exceptionDetails.text+': '+msg.params.exceptionDetails.exception?.description);};
 const send=(method,params={})=>new Promise((resolve,reject)=>{const id=++seq;pending.set(id,{resolve,reject});ws.send(JSON.stringify({id,method,params}));});
 const evaluate=async(expression)=>{const r=await send('Runtime.evaluate',{expression,awaitPromise:true,returnByValue:true});if(r.exceptionDetails)throw new Error(r.exceptionDetails.exception?.description||'Evaluation failed');return r.result.value;};
 const wait=async(expression)=>{for(let i=0;i<240;i++){if(await evaluate(expression))return;await new Promise(r=>setTimeout(r,150));}console.log(await evaluate('({url:location.href,body:document.body.innerText.slice(0,3000)})'));console.log(errors);throw new Error(`Timed out: ${expression}`);};
 const click=async(text)=>{await evaluate(`(()=>{const b=[...document.querySelectorAll('button')].find(b=>b.textContent.trim()===${JSON.stringify(text)});if(!b)throw new Error('Button missing: '+${JSON.stringify(text)});b.click()})()`);};

 const aria=async(label)=>evaluate(`document.querySelector(${JSON.stringify(`button[aria-label="${label}"]`)}).click()`);
 const choose=async(label)=>{await wait('!![...document.querySelectorAll("dialog button")].find(b=>b.textContent.trim().startsWith('+JSON.stringify(label)+')&&!b.disabled)');await evaluate('[...document.querySelectorAll("dialog button")].find(b=>b.textContent.trim().startsWith('+JSON.stringify(label)+')).click()');};
 const state=()=>evaluate('JSON.parse(localStorage.getItem("room-economy-v1"))');
 const close=()=>evaluate(`document.querySelector('dialog button[aria-label="Close dialog"]').click()`);
 const ready=()=>wait('!!document.querySelector("canvas")&&!document.querySelector(".world-loading")');

 intercept=async({requestId,request})=>{
   try{
    let body,status=200;
    if(request.url.includes('/gemini/audit')){
     const input=JSON.parse(request.postData);auditRequests.push(input);const valid=input.jars.food>=240&&Object.values(input.jars).reduce((a,b)=>a+b,0)<=input.income;
     body={success:true,source:'gemini',data:{isValid:valid,riskRating:valid?'LOW':'HIGH',commentary:valid?'Your essentials fit this plan.':'Food is underfunded. Keep room for groceries.',recommendedAdjustments:{...input.jars,food:240}}};await new Promise(r=>setTimeout(r,250));
    }else if(request.url.includes('/gemini/day')){
     const input=JSON.parse(request.postData);reviewRequests.push(input);
     const g=input.state,day=(g.metrics.turn-1)%30+1,warning=g.jars.leisure.spentAmount>=150;
     if(failReview){status=503;body={success:false,error:'Test outage'};}
     else body={success:true,source:'gemini',data:{assessedDay:g.metrics.turn,kind:input.kind,source:'gemini',analysis:{isWarning:warning,ending:severe?severeKind:'none',failureConfidence:severe?1:0,riskRating:severe?'CRITICAL':warning?'HIGH':'LOW',commentary:warning?'OMG, yesterday I bought too much. Now rent wants a word.':'Your wallet made it through today without calling for backup.',reason:warning?'Spending pace threatens upcoming essential bills.':'Essentials remain covered.',recoverySteps:['Keep rent and food money reserved.'],behavior:warning?'worried':'calm'},forecast:{day,daysRemaining:30-day,todaySpent:g.transactions.filter(t=>t.gameDay===g.metrics.turn&&t.kind==='purchase').reduce((n,t)=>n+t.amount,0),variableSpent:g.jars.food.spentAmount+g.jars.leisure.spentAmount+g.jars.transit.spentAmount,essentialsRemaining:1320,projectedBalance:warning?-100:1000,safeDailySpend:35,riskReasons:warning?['Future bill risk']:[]},transactionIds:g.transactions.filter(t=>t.gameDay===g.metrics.turn).map(t=>t.id)}};
     await new Promise(r=>setTimeout(r,250));
    }else {
     bankSyncs++;const transactions=[...([{id:'bank-saving',amount:150,description:'Savings transfer',category:'savings',kind:'saving'},{id:'bank-gym',amount:25,description:'Gym membership',category:'leisure',kind:'purchase'},{id:'bank-health',amount:30,description:'Pharmacy',category:'leisure',kind:'purchase'}].map(t=>({...t,payerId:'bank',medium:'balance',paymentDate:'2026-09-11'}))),{id:'bank-food',payerId:'bank',medium:'balance',paymentDate:'2026-09-11',amount:42.5,description:'Grocery market',category:'food',kind:'purchase'}];
     if(bankSyncs>1)transactions.push({id:'bank-shop',payerId:'bank',medium:'balance',paymentDate:'2026-09-11',amount:160,description:'Shopping',category:'leisure',kind:'purchase'});
     body={success:true,source:'nessie',data:{balance:bankSyncs>1?2940:3100,transactions,accountName:'Test checking'}};
    }
    await send('Fetch.fulfillRequest',{requestId,responseCode:status,responseHeaders:[{name:'Content-Type',value:'application/json'}],body:Buffer.from(JSON.stringify(body)).toString('base64')});
   }catch(e){errors.push(String(e));}
 };
 await send('Runtime.enable');await send('Page.enable');await send('Emulation.setEmulatedMedia',{features:[{name:'prefers-reduced-motion',value:'no-preference'}]});await send('Fetch.enable',{patterns:[{urlPattern:'*/api/gemini/audit',requestStage:'Request'},{urlPattern:'*/api/gemini/day',requestStage:'Request'},{urlPattern:'*/api/nessie/sync',requestStage:'Request'}]});
 await send('Emulation.setDeviceMetricsOverride',{width:1440,height:900,deviceScaleFactor:1,mobile:false});await send('Page.navigate',{url:'http://localhost:3000'});await ready();await send('Page.navigate',{url:'about:blank'});await wait('location.href==="about:blank"');await send('Storage.clearDataForOrigin',{origin:'http://localhost:3000',storageTypes:'local_storage'});await send('Page.navigate',{url:'http://localhost:3000'});await ready();await new Promise(r=>setTimeout(r,500));
 await aria('Open game menu');await choose('Start a new run');await choose('Create new run');await wait('!!document.querySelector(".budget-check")');assert.equal(auditRequests.length,0);
 await evaluate(`(()=>{const input=document.querySelector('input[name="allocations.food"]');Object.getOwnPropertyDescriptor(HTMLInputElement.prototype,"value").set.call(input,"0");input.dispatchEvent(new Event("input",{bubbles:true}));})()`);await click('Check with Gemini');await wait('!!document.querySelector(".budget-review")');assert.equal(auditRequests.length,1);assert.equal(auditRequests[0].jars.food,0);assert.ok(await evaluate('document.querySelector(".budget-review").textContent.includes("needs another look")'));
 await evaluate('document.querySelector(".setup-actions").scrollIntoView({block:"end"})');
 const setup=await send('Page.captureScreenshot',{format:'png'});await writeFile(path.join(output,'budget-check.png'),Buffer.from(setup.data,'base64'));
 await evaluate(`(()=>{const input=document.querySelector('input[name="allocations.food"]');Object.getOwnPropertyDescriptor(HTMLInputElement.prototype,"value").set.call(input,"400");input.dispatchEvent(new Event("input",{bubbles:true}));})()`);await wait('!document.querySelector(".budget-review")');assert.equal(auditRequests.length,1);await close();
 assert.equal(await evaluate('document.querySelector(".visible-balance").textContent'),'$3,000.00');
 assert.equal(await evaluate('document.querySelectorAll(".balance-actions button").length'),5);
 assert.equal(await evaluate('document.documentElement.scrollHeight<=innerHeight&&document.documentElement.scrollWidth<=innerWidth'),true);
 const reviewBounds=()=>evaluate('(()=>{const r=document.querySelector(".review-panel").getBoundingClientRect();return {x:r.x,y:r.y,width:r.width,height:r.height}})()');const reviewBefore=await reviewBounds();
 await evaluate('document.querySelector(".missions-toggle").click()');await wait('document.querySelector(".missions-toggle").getAttribute("aria-expanded")==="true"');assert.deepEqual(await reviewBounds(),reviewBefore,'Opening missions must not resize or move the daily review');assert.ok(await evaluate('(()=>{const m=document.querySelector(".mission-list").getBoundingClientRect(),r=document.querySelector(".review-panel").getBoundingClientRect();return Math.abs(m.width-r.width)<1&&m.bottom>r.top&&m.top<r.bottom})()'),'Matching-width missions overlap daily review');
 const missionsShot=await send('Page.captureScreenshot',{format:'png'});await writeFile(path.join(output,'missions-overlay.png'),Buffer.from(missionsShot.data,'base64'));await evaluate('document.querySelector(".missions-toggle").click()');
 assert.ok(await evaluate('document.querySelector(".scene-controls").textContent.includes("110%")'),'Room starts slightly larger');
 const dragRoom=async(degrees)=>{
 const r=await evaluate('(()=>{const r=document.querySelector("canvas").getBoundingClientRect();return {x:r.x,y:r.y,width:r.width,height:r.height}})()');const x=r.x+r.width*.25,y=r.y+r.height*.55,dx=r.width*degrees/360;
 await send('Input.dispatchMouseEvent',{type:'mousePressed',x,y,button:'left',clickCount:1});for(let n=1;n<=8;n++){await send('Input.dispatchMouseEvent',{type:'mouseMoved',x:x+dx*n/8,y,buttons:1});await new Promise(r=>setTimeout(r,25));}await send('Input.dispatchMouseEvent',{type:'mouseReleased',x:x+dx,y,button:'left',clickCount:1});await new Promise(r=>setTimeout(r,450));
 };
 assert.equal(await evaluate('getComputedStyle(document.querySelector(".game-world")).backgroundColor'),'rgb(39, 50, 45)','Original surrounding UI restored');assert.equal(await evaluate('!!document.querySelector(".balance-panel .review-status")'),false);assert.ok(await evaluate('!!document.querySelector(".left-panels .review-panel")'));
 await aria('Zoom in');await aria('Zoom in');await aria('Zoom in');await aria('Zoom in');await wait('document.querySelector(".scene-controls").textContent.includes("150%")');assert.ok(await evaluate('[...document.querySelectorAll("button")].find(b=>b.getAttribute("aria-label")==="Zoom in").disabled'));
 for(let n=0;n<8;n++){await dragRoom(45);const zoomFrame=await send('Page.captureScreenshot',{format:'png'});await writeFile(path.join(output,'zoom-check.png'),Buffer.from(zoomFrame.data,'base64'));assert.equal(await evaluate('!!document.querySelector("dialog[open]")'),false,'Dragging does not inspect furniture');assert.ok(await evaluate('(()=>{const c=document.querySelector("canvas"),p=c.getContext("2d").getImageData(0,0,c.width,c.height).data;for(let x=0;x<c.width;x++)if(p[x*4+3]||p[((c.height-1)*c.width+x)*4+3])return false;for(let y=0;y<c.height;y++)if(p[y*c.width*4+3]||p[(y*c.width+c.width-1)*4+3])return false;return true;})()'),'Room edges remain inside padded canvas at maximum zoom');}
 assert.ok(await evaluate('document.querySelector(".scene-controls output").textContent.includes("0°")'));await aria('Reset room view');await dragRoom(45);
 let rotated=await send('Page.captureScreenshot',{format:'png'});await writeFile(path.join(output,'rotated.png'),Buffer.from(rotated.data,'base64'));await aria('Reset room view');await new Promise(r=>setTimeout(r,500));
 assert.ok(await evaluate('document.querySelector(".scene-controls").getBoundingClientRect().bottom<document.querySelector(".character-thought").getBoundingClientRect().top'),'Camera controls clear dialogue');
 let shot=await send('Page.captureScreenshot',{format:'png'});await writeFile(path.join(output,'desktop.png'),Buffer.from(shot.data,'base64'));
 const fridgePoint=await evaluate('(()=>{const r=document.querySelector("canvas").getBoundingClientRect();return {x:r.x+r.width*603.04/1280,y:r.y+r.height*317.42/960}})()');await send('Input.dispatchMouseEvent',{type:'mousePressed',...fridgePoint,button:'left',clickCount:1});await send('Input.dispatchMouseEvent',{type:'mouseReleased',...fridgePoint,button:'left',clickCount:1});await wait('document.querySelector("dialog h2")?.textContent==="The fridge"');await close();
 const action=async(label,amount,submit)=>{
  await wait('![...document.querySelectorAll(".balance-actions button")].find(b=>b.textContent.includes('+JSON.stringify(label)+')).disabled');
  await evaluate('[...document.querySelectorAll(".balance-actions button")].find(b=>b.textContent.includes('+JSON.stringify(label)+')).click()');
  await wait('!!document.querySelector("dialog input[type=number]")');assert.equal(await evaluate('document.querySelector("dialog input[type=number]").value'),'','Amount must start blank');
  await evaluate('(()=>{const input=document.querySelector("dialog input[type=number]");Object.getOwnPropertyDescriptor(HTMLInputElement.prototype,"value").set.call(input,'+JSON.stringify(String(amount))+');input.dispatchEvent(new Event("input",{bubbles:true}));input.dispatchEvent(new Event("change",{bubbles:true}));})()');
  await choose(submit);await wait('!document.querySelector("dialog[open]")');
 };
 await action('Groceries',83.75,'Bring home groceries');assert.equal((await state()).metrics.cashBalance,2916.25);assert.equal((await state()).transactions[0].gameDay,1);
 await action('Shopping & fun',160,'Treat myself');assert.equal((await state()).metrics.cashBalance,2756.25);
 await new Promise(r=>setTimeout(r,1500));assert.equal(reviewRequests.length,0,'Spending must not request analysis');
 await wait('!document.querySelector(".end-week").disabled');await evaluate('(()=>{const b=document.querySelector(".end-week");b.click();b.click();})()');
 await wait('document.querySelector(".balance-calendar").textContent.includes("Day 2 / 30")');
 await wait('JSON.parse(localStorage.getItem("room-economy-v1")).reviews.some(r=>r.kind==="close"&&r.assessedDay===1)');
 assert.equal((await state()).metrics.turn,2);assert.ok((await state()).progression.coins<0);assert.ok((await state()).dialogue.some(d=>d.kind==='warning'));assert.equal((await state()).command.behavior,'worried');const closing=reviewRequests.find(r=>r.kind==='close');assert.equal(closing.state.metrics.turn,1);assert.equal(closing.state.transactions.filter(t=>t.gameDay===1).length,2);
 await click('Forecast & next steps');await wait('document.querySelector("dialog h2")?.textContent==="Forecast & next steps"');assert.ok(await evaluate('document.querySelector("dialog").textContent.includes("Keep rent and food money reserved.")'));await close();
 const keysPoint=await evaluate('(()=>{const r=document.querySelector("canvas").getBoundingClientRect();return {x:r.x+r.width*513.28/1280,y:r.y+r.height*516.96/960}})()');await send('Input.dispatchMouseEvent',{type:'mousePressed',...keysPoint,button:'left',clickCount:1});await send('Input.dispatchMouseEvent',{type:'mouseReleased',...keysPoint,button:'left',clickCount:1});await wait('document.querySelector("dialog h2")?.textContent==="Your keys"');assert.ok(await evaluate('!!document.querySelector("dialog input[type=number]")'));await close();
 const currentBalance=(await state()).metrics.cashBalance;await action('Transport',12.5,'Head out');assert.equal((await state()).metrics.cashBalance,currentBalance-12.5);
 await wait('!document.querySelector(".end-week").disabled');await evaluate('document.querySelector(".end-week").click()');await wait('JSON.parse(localStorage.getItem("room-economy-v1")).reviews.some(r=>r.kind==="close"&&r.assessedDay===2)');
 const dayTwo=(await state()).reviews.find(r=>r.kind==='close'&&r.assessedDay===2);assert.equal(dayTwo.transactionIds.length,1);assert.equal(dayTwo.forecast.todaySpent,12.5);
 failReview=true;await wait('!document.querySelector(".end-week").disabled');await evaluate('document.querySelector(".end-week").click()');await wait('JSON.parse(localStorage.getItem("room-economy-v1")).reviews.some(r=>r.kind==="close"&&r.assessedDay===3)');assert.equal((await state()).reviews[0].source,'fallback');assert.equal((await state()).metrics.turn,4);failReview=false;
 await send('Page.reload');await ready();assert.equal((await state()).metrics.turn,4);assert.ok((await state()).reviews.some(r=>r.assessedDay===1&&r.kind==='close'));
 await wait('!document.querySelector(".sync-life").disabled');await evaluate('document.querySelector(".sync-life").click()');await choose('Connect Nessie account');await wait('!document.querySelector("dialog[open]")');assert.equal((await state()).mode,'nessie');assert.equal((await state()).metrics.cashBalance,3100);assert.equal((await state()).transactions.length,4);assert.equal((await state()).progression.coins,140);
 await wait('!document.querySelector(".sync-life").disabled');await evaluate('document.querySelector(".sync-life").click()');await wait('JSON.parse(localStorage.getItem("room-economy-v1")).transactions.length===5');assert.equal((await state()).metrics.cashBalance,2940);assert.equal((await state()).jars.food.spentAmount,42.5);

 const reviewCount=reviewRequests.length;await new Promise(r=>setTimeout(r,1200));assert.equal(reviewRequests.length,reviewCount);assert.equal((await state()).progression.coins,140);
 await evaluate('document.querySelector(".shop-toggle").click()');await choose('120 coins');await wait('JSON.parse(localStorage.getItem("room-economy-v1")).progression.owned.includes("house")');assert.equal((await state()).progression.coins,20);await close();
 await send('Emulation.setDeviceMetricsOverride',{width:375,height:812,deviceScaleFactor:1,mobile:false});await new Promise(r=>setTimeout(r,300));assert.equal(await evaluate('document.documentElement.scrollWidth<=innerWidth'),true,'No mobile horizontal overflow');assert.ok(await evaluate('!!document.querySelector(".balance-panel .sync-life")'));assert.ok(await evaluate('document.querySelector(".scene-controls").getBoundingClientRect().bottom<document.querySelector(".character-thought").getBoundingClientRect().top'),'Mobile camera controls clear dialogue');shot=await send('Page.captureScreenshot',{format:'png',captureBeyondViewport:true});await writeFile(path.join(output,'mobile.png'),Buffer.from(shot.data,'base64'));
 const endingBase=await state();severe=true;await evaluate('(()=>{const s=JSON.parse(localStorage.getItem("room-economy-v1"));s.metrics.cashBalance=100;localStorage.setItem("room-economy-v1",JSON.stringify(s));})()');await send('Page.reload');await ready();await wait('!document.querySelector(".end-week").disabled');await evaluate('document.querySelector(".end-week").click()');await wait('JSON.parse(localStorage.getItem("room-economy-v1")).ending.phase==="playing"');assert.equal(await evaluate('!!document.querySelector("dialog[open]")'),false);await wait('JSON.parse(localStorage.getItem("room-economy-v1")).ending.phase==="complete"');await wait('!!document.querySelector("dialog[open]")');assert.ok(await evaluate('document.querySelector("dialog").textContent.includes("essential")'));assert.equal(await evaluate('document.querySelectorAll(".ending-choices button").length'),2);assert.ok(await evaluate('!document.querySelector("dialog").textContent.includes("Live with a new plan")'));
 for(const kind of ['food_shortage','power_cut','exhaustion']){
 severeKind=kind;const fixture=structuredClone(endingBase);fixture.metrics.cashBalance=100;
 await evaluate('localStorage.setItem("room-economy-v1",'+JSON.stringify(JSON.stringify(fixture))+')');await send('Page.reload');await ready();await wait('!document.querySelector(".end-week").disabled');await evaluate('document.querySelector(".end-week").click()');await wait('JSON.parse(localStorage.getItem("room-economy-v1")).ending.phase==="playing"');await new Promise(r=>setTimeout(r,3900));assert.equal(await evaluate('!!document.querySelector("dialog[open]")'),false,kind+' must animate before dialog');
 const frame=await send('Page.captureScreenshot',{format:'png'});await writeFile(path.join(output,'ending-'+kind+'.png'),Buffer.from(frame.data,'base64'));await wait('JSON.parse(localStorage.getItem("room-economy-v1")).ending.phase==="complete"');await wait('!!document.querySelector("dialog[open]")');
 }
 assert.deepEqual(errors,[],'No browser runtime errors');
 const report={passed:true,providerMode:'Mocked provider responses for reproducibility; live Gemini was not called by this test.',checks:['Balance visible on right with five action buttons and bank-only missions','Amount inputs blank and arbitrary cents accepted','Positive-balance warning is highlighted','No spending analysis until End day','Setup budget check sends current categories only on click','Changing categories clears stale setup feedback','Bank missions reward once','Coins buy house upgrades','Ending animation precedes recovery dialog','Gemini warning changes character command','End day advances once and reviews the old day','Second day review excludes previous-day transactions','Review outage uses labeled fallback without double progression','Days and reviews survive reload','Update button connects and deduplicates bank transactions','Mobile controls remain accessible','Hold-and-drag rotation without accidental item clicks','Click-to-inspect works after rotation and zoom','Unclipped maximum zoom across all eight camera angles','Original surrounding UI restored','Gemini review in separate left panel','Camera controls clear dialogue on desktop and mobile','No browser runtime errors'],screenshots:['desktop.png','mobile.png']};await writeFile(path.join(output,'browser-smoke.json'),JSON.stringify(report,null,2));console.log(JSON.stringify(report,null,2));

}finally{ws?.close();chrome.kill();}

